apiVersion: v1
kind: Service
metadata:
  name: crypto
  labels:
    team: c4po
spec:
  selector:
    name: crypto
    serving: "true"
  ports:
    - port: 443
      name: https
      targetPort: 8443
